updated readme

diff --git a/_CI/scripts/bootstrap b/_CI/scripts/bootstrap
--- a/_CI/scripts/bootstrap
+++ b/_CI/scripts/bootstrap
@@ -1,22 +1,22 @@
 #!/bin/bash
 cd $(dirname $0)/../..
 
-source $(which virtualenvwrapper.sh)
+#source $(which virtualenvwrapper.sh)
 
-[ -z "$WORKON_HOME" ] && WORKON_HOME=$HOME/.virtualenvs
+#[ -z "$WORKON_HOME" ] && WORKON_HOME=$HOME/.virtualenvs
 
-if (! test -d "$WORKON_HOME/toonlib")
-then
-  echo "Creating virtual env for toonlib"
-  if (! mkvirtualenv "toonlib" )
-  then
-    echo "Missing prerequisite virtualenvwrapper, bailing out"
-    exit 1
-  fi
-fi
+#if (! test -d "$WORKON_HOME/toonlib")
+#then
+#  echo "Creating virtual env for toonlib"
+#  if (! mkvirtualenv "toonlib" )
+#  then
+#    echo "Missing prerequisite virtualenvwrapper, bailing out"
+#    exit 1
+#  fi
+#fi
 
 echo "Working on virtualenv toonlib"
-source "$WORKON_HOME/toonlib/bin/activate"
+source ".venv/bin/activate"
 
 echo "Installing python package requirements.."
 pip install -r requirements.txt
